### ISSUE TITLE
... not found in Terraform schema

### ISSUE THREAD

**Issue by ezlo-eugenek** [sl1pm4t/k2tf#23]
1:21PM Warn | excluding attribute [kubernetes_limit_range.spec.limits] not found in Terraform schema 

1:21PM Warn | excluding attribute [kubernetes_deployment.spec.template.spec.image_pull_secret] not found in Terraform schema 

LimitRange config:
```apiVersion: v1
kind: LimitRange
metadata:
  name: ns-limit-range
  namespace: ${ENVIRONMENT}
spec:
  limits:
  - default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    max:
      cpu: 2
      memory: 12Gi
    min:
      cpu: 10m
      memory: 10Mi
    type: Container```



ImagePullSecret:

... 
     imagePullSecrets:
      - name: regcred
...

**Comment by sl1pm4t** [comment]
Hi @ezlo-eugenek 
This should be fixed in the latest build (v0.2.4).
Thanks.
