### ISSUE TITLE
skipping API object, kind not supported by Terraform provider.  kind=CronJob

### ISSUE THREAD

**Issue by ezlo-eugenek** [sl1pm4t/k2tf#24]
But as I can see it is supported:
https://www.terraform.io/docs/providers/kubernetes/r/cron_job.html

**Comment by sl1pm4t** [comment]
Ok, it looks like these were added 2 days ago:
https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/CHANGELOG.md

I'll update the k2tf dependencies to pull in this new version.

**Comment by sl1pm4t** [comment]
Hi @ezlo-eugenek 
This should be fixed in the latest build (v0.2.4).
Thanks.
