### ISSUE TITLE
Converting official kured 1.2 yaml spec results in daemonset that crash loops

### ISSUE THREAD

**Issue by landro** [sl1pm4t/k2tf#35]
When I convert the official kured 1.2 [spec](
https://github.com/weaveworks/kured/releases/download/1.2.0/kured-1.2.0-dockerhub.yaml), I get a terraform config that crash loops when applied.

It seems the reason is the automount_service_account_token defaults to false in the terraform provider due to the following line.

https://github.com/terraform-providers/terraform-provider-kubernetes/blob/077ff93ef66cdb66148e12fc1d629d53b2203678/kubernetes/resource_kubernetes_pod.go#L21

Would it make sense to set this flag explicitly to true in k2tf, since this is the [k8s default](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/)

**Comment by sl1pm4t** [comment]
Hi @landro - while I'm I agree the default should be `true`, I don't think this tool is the right place to enforce that value. 

The good news is that it looks like this will be fixed in the Terraform Provider soon:
https://github.com/terraform-providers/terraform-provider-kubernetes/pull/261
