### ISSUE TITLE
Add reverse functionality

### ISSUE THREAD

**Issue by matttrach** [sl1pm4t/k2tf#42]
It would be cool to have a way to create k8 configs from Terraform resources. 

This would allow k8 admins who do not have a lot of Terraform experience to review what the Terraform provider was going to do in the planning stage in k8 terms. 

We could also use this to lint the k8 output and further verify our Terraform output.

**Comment by sl1pm4t** [comment]
Hi @matttrach - I've had similar thoughts about this too, but I think it makes most sense to put that kind of functionality into the Terraform Kubernetes provider. To convert a Terraform resource back into a K8S object, k2tf would have to be able to fully process the Terraform resource graph, render templates, interpolate variables etc. - all of which Terraform + the provider can already do.
