### ISSUE TITLE
But does it go in reverse??

### ISSUE THREAD

**Issue by MaxFlanders** [sl1pm4t/k2tf#55]
Great tool! Being able to go from .tf to .yaml would also be nice :D

Thanks!!

**Comment by jhonatanmorais** [comment]
Most part of GitOps and k8s ecossytem tools work with yaml files and this option would be so nice!

**Comment by sl1pm4t** [comment]
@MaxFlanders / @jhonatanmorais could you walk me through the use case / workflow that you see would benefit from this functionality?

**Comment by sl1pm4t** [comment]
Closing as dup of #42
