### ISSUE TITLE
skipping API object, kind not supported by Terraform provider.  kind=ValidatingWebhookConfiguration

### ISSUE THREAD

**Issue by jcreager** [sl1pm4t/k2tf#67]
Thank you for this very useful tool.

I observed an issue where this tool will not convert `ValidatingWebhookConfiguration` objects.

##### Version:

```
k2tf --version
k2tf version: 0.4.1
```

##### Steps to reproduce:

1. Run the following command to convert the manifests files for Kubernetes `ingress-nginx`.

```
wget -qO- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.34.1/deploy/static/provider/cloud/deploy.yaml | k2tf
```

##### Expected result:

k2tf will convert yaml manifest for ValidatingWebhookConfiguration object to HCL.

##### Actual result:

```
3:21PM Warn | skipping API object, kind not supported by Terraform provider.  kind=ValidatingWebhookConfiguration
```

##### Other info:

According to the current TF docs, ValidatingWebhookConfiguration (kubernetes_validating_webhook_configuration) is supported.  https://www.terraform.io/docs/providers/kubernetes/r/validating_webhook_configuration.html

Let me know if I can provide any additional info.  Thanks!

**Comment by sl1pm4t** [comment]
Hi @jcreager  this should be fixed in the latest release.
https://github.com/sl1pm4t/k2tf/releases/tag/v0.5.0

**Comment by jcreager** [comment]
Thanks @sl1pm4t!
