### ISSUE TITLE
does k2tf support conversion of multiple yaml docs to tf file

### ISSUE THREAD

**Issue by vakkur** [sl1pm4t/k2tf#73]
I want to covert yaml with multiple docs.Does k2tf support it

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/part-of: argocd
  name: argocd-dex-server

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/part-of: argocd
  name: argocd-dex-server
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch

**Comment by sl1pm4t** [comment]
Yes it should be able to do this so long as each YAML doc is delimited with `---`
