### ISSUE TITLE
kubernetes_{daemonset,deployment}: set automount_service_account_token to true

### ISSUE THREAD

**Issue by flokli** [sl1pm4t/k2tf#78]
Contrary to the kubernetes defaults, the kubernetes terraform provider hardcodes automount_service_account_token to `false`:

https://github.com/hashicorp/terraform-provider-kubernetes/issues/38

However, this leads to non-working resources being created, as they rely on that defaulting to true.

k2tf should add

```
automount_service_account_token = true
```

**Comment by meroupatate** [comment]
thank you @flokli i spent two days trying to figure out what was wrong with my deployment and my daemonset 😭

**Comment by flokli** [comment]
@meroupatate sorry to hear. If there really needs to be this deviation from the defaults, it should really be documented loudly…

**Comment by flokli** [comment]
It seems terraform-provider-kubernetes pedalled back, and switched over to use the k8s defaults again: https://github.com/hashicorp/terraform-provider-kubernetes/pull/1054

**Comment by sl1pm4t** [comment]
I think this is resolved upstream (as pointed out above by @flokli ), so going to close this.
